# Generated by Django 5.2.9 on 2025-12-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AddField(
            model_name='project',
            name='page',
            field=models.CharField(choices=[('python', 'Python'), ('powerbi', 'Power BI'), ('excel', 'Excel'), ('automacoes', 'Automações')], default='python', max_length=20, verbose_name='Página'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Imagem'),
        ),
    ]
