# Generated by Django 5.2.9 on 2025-12-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_project_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='page',
            field=models.CharField(choices=[('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('excel', 'Excel'), ('automacoes', 'Automações')], max_length=20, verbose_name='Página'),
        ),
    ]
