# Generated by Django 5.2.9 on 2025-12-31 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200, verbose_name='Título do Banner')),
                ('banner_subtitle', models.CharField(max_length=255, verbose_name='Subtítulo do Banner')),
                ('folha1_texto', models.TextField(verbose_name='Texto da Folha 1')),
                ('folha2_texto', models.TextField(verbose_name='Texto da Folha 2')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículo',
            },
        ),
    ]
