# Generated by Django 5.2.9 on 2026-01-02 16:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel'), ('curriculo', 'Currículo'), ('contato', 'Contato')], max_length=30, unique=True, verbose_name='Página')),
                ('titulo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hero – Título')),
                ('titulo_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do título')),
                ('subtitulo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hero – Subtítulo')),
                ('subtitulo_color', models.CharField(default='#cbd5e1', max_length=7, verbose_name='Cor do subtítulo')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto principal')),
                ('texto_color', models.CharField(default='#e5e7eb', max_length=7, verbose_name='Cor do texto')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/banners/', verbose_name='Banner da página')),
                ('menu_conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Menu – Conteúdo')),
                ('menu_bg_color', models.CharField(default='#0f172a', max_length=7, verbose_name='Menu – Cor de fundo')),
                ('menu_text_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Menu – Cor do texto')),
                ('services_title_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Título')),
                ('services_text_color', models.CharField(default='#334155', max_length=7, verbose_name='Serviços – Texto')),
                ('services_border_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Borda')),
                ('services_button_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Botão')),
                ('projects_title_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Título')),
                ('projects_text_color', models.CharField(default='#334155', max_length=7, verbose_name='Projetos – Texto')),
                ('projects_border_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Borda')),
                ('projects_button_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Botão')),
                ('footer_conteudo', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Footer – Conteúdo')),
                ('footer_bg_color', models.CharField(default='#020617', max_length=7, verbose_name='Footer – Cor de fundo')),
                ('footer_text_color', models.CharField(default='#cbd5e1', max_length=7, verbose_name='Footer – Cor do texto')),
                ('curriculo_folha_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Currículo – Folha 1')),
                ('curriculo_folha_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Currículo – Folha 2')),
                ('curriculo_pdf', models.FileField(blank=True, null=True, upload_to='curriculo/pdf/', verbose_name='Currículo – PDF')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Texto')),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(limit_choices_to={'slug': 'contato'}, on_delete=django.db.models.deletion.CASCADE, to='web.page')),
            ],
        ),
        migrations.CreateModel(
            name='AutomacoesPage',
            fields=[
            ],
            options={
                'verbose_name': 'Automações',
                'verbose_name_plural': 'Automações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='CurriculoPage',
            fields=[
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='ExcelPage',
            fields=[
            ],
            options={
                'verbose_name': 'Excel',
                'verbose_name_plural': 'Excel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PowerBIPage',
            fields=[
            ],
            options={
                'verbose_name': 'Power BI',
                'verbose_name_plural': 'Power BI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PythonPage',
            fields=[
            ],
            options={
                'verbose_name': 'Python',
                'verbose_name_plural': 'Python',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('slug', models.SlugField()),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='web.page')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('slug', models.SlugField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='web.page')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
