# Generated by Django 5.2.9 on 2025-12-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='curriculo/banner/', verbose_name='Imagem do Banner'),
        ),
    ]
