# Generated by Django 5.2.9 on 2026-01-02 17:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutomacoesPage',
        ),
        migrations.DeleteModel(
            name='CurriculoPage',
        ),
        migrations.DeleteModel(
            name='ExcelPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='PowerBIPage',
        ),
        migrations.DeleteModel(
            name='PythonPage',
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='texto',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='curriculo_folha_1',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Currículo – Folha 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='curriculo_folha_2',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Currículo – Folha 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=30, unique=True, verbose_name='Slug da página (ex: home, python, powerbi)'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Hero – Subtítulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Texto principal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='titulo',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Hero – Título'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='descricao',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='imagem',
            field=models.ImageField(default='', upload_to='projects/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='descricao',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
