# Generated by Django 5.2.9 on 2026-01-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_delete_automacoespage_delete_curriculopage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='footer_conteudo',
        ),
        migrations.RemoveField(
            model_name='page',
            name='menu_conteudo',
        ),
    ]
