# Generated by Django 5.2.9 on 2025-12-31 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_curriculo_banner_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculo',
            options={},
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='folha1_texto',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='folha2_texto',
        ),
        migrations.AddField(
            model_name='curriculo',
            name='subtitulo_banner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculo',
            name='texto_folha_1',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculo',
            name='texto_folha_2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculo',
            name='titulo_banner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='curriculo/banner/'),
        ),
    ]
