# Generated by Django 5.2.9 on 2025-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_curriculo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Tema Principal', max_length=100, verbose_name='Nome do Tema')),
                ('cor_titulo', models.CharField(default='#ffffff', help_text='Cor dos títulos principais (ex: #ffffff)', max_length=7, verbose_name='Cor do Título')),
                ('cor_subtitulo', models.CharField(default='#38bdf8', help_text='Cor dos subtítulos (ex: #38bdf8)', max_length=7, verbose_name='Cor do Subtítulo')),
                ('cor_texto', models.CharField(default='#e5e7eb', help_text='Cor do texto padrão (ex: #e5e7eb)', max_length=7, verbose_name='Cor do Texto')),
                ('cor_botao', models.CharField(default='#38bdf8', help_text='Cor principal dos botões (ex: #38bdf8)', max_length=7, verbose_name='Cor do Botão')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
            ],
            options={
                'verbose_name': 'Tema do Site',
                'verbose_name_plural': 'Temas do Site',
            },
        ),
        migrations.AlterModelOptions(
            name='curriculo',
            options={'verbose_name': 'Currículo', 'verbose_name_plural': 'Currículos'},
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='curriculo/banner/', verbose_name='Imagem do Banner'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='subtitulo_banner',
            field=models.CharField(max_length=200, verbose_name='Subtítulo do Banner'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='texto_folha_1',
            field=models.TextField(verbose_name='Texto da Folha 1'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='texto_folha_2',
            field=models.TextField(verbose_name='Texto da Folha 2'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='titulo_banner',
            field=models.CharField(max_length=200, verbose_name='Título do Banner'),
        ),
        migrations.AlterField(
            model_name='curriculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
