# Generated by Django 5.2.9 on 2025-12-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_sitetheme_alter_curriculo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='pagina',
            field=models.CharField(choices=[('global', 'Global'), ('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel'), ('curriculo', 'Currículo'), ('contato', 'Contato')], default='global', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='cor_botao',
            field=models.CharField(default='#38bdf8', help_text='Cor principal dos botões', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='cor_subtitulo',
            field=models.CharField(default='#38bdf8', help_text='Cor dos subtítulos', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='cor_texto',
            field=models.CharField(default='#e5e7eb', help_text='Cor do texto padrão', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='cor_titulo',
            field=models.CharField(default='#ffffff', help_text='Cor dos títulos principais', max_length=7),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
