# Generated by Django 5.2.9 on 2026-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_sitetheme_pagina_alter_sitetheme_cor_botao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetheme',
            name='cor_botao',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='cor_subtitulo',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='cor_texto',
        ),
        migrations.RemoveField(
            model_name='sitetheme',
            name='cor_titulo',
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='hero_subtitle_color',
            field=models.CharField(default='#38bdf8', help_text='Subtítulo do banner', max_length=7, verbose_name='Cor do subtítulo'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='hero_title_color',
            field=models.CharField(default='#fde047', help_text='Título principal do banner', max_length=7, verbose_name='Cor do título principal'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='menu_color',
            field=models.CharField(default='#ffffff', help_text='Cor dos links do menu', max_length=7, verbose_name='Cor do menu'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='projects_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos - Cor da borda'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='projects_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos - Cor do botão'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='projects_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Projetos - Cor da descrição'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='projects_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos - Cor do título'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='services_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços - Cor da borda'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='services_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços - Cor do botão'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='services_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Serviços - Cor da descrição'),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='services_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços - Cor do título'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Tema'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='pagina',
            field=models.CharField(choices=[('global', 'Global'), ('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel'), ('curriculo', 'Currículo'), ('contato', 'Contato')], default='global', max_length=20, verbose_name='Página'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última atualização'),
        ),
    ]
