# Generated by Django 5.2.9 on 2026-01-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_sitetheme_cor_botao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Entre em contato', max_length=200, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto de apresentação')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contato – Conteúdo',
                'verbose_name_plural': 'Contato – Conteúdo',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_principal', models.CharField(max_length=200, verbose_name='Título principal (Home)')),
                ('subtitulo', models.CharField(max_length=300, verbose_name='Subtítulo (Home)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home – Conteúdo',
                'verbose_name_plural': 'Home – Conteúdo',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina', models.CharField(choices=[('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel')], max_length=30, unique=True, verbose_name='Página')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da página')),
                ('texto', models.TextField(verbose_name='Texto principal')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página – Conteúdo',
                'verbose_name_plural': 'Páginas – Conteúdo',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do projeto')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição curta')),
                ('imagem', models.ImageField(upload_to='projects/', verbose_name='Imagem do projeto')),
                ('slug', models.SlugField(help_text='URL do projeto', unique=True)),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do serviço')),
                ('descricao', models.TextField(max_length=300, verbose_name='Descrição do serviço')),
                ('slug', models.SlugField(help_text='Usado para redirecionamento da página', unique=True)),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='hero_subtitle_color',
            field=models.CharField(default='#38bdf8', max_length=7, verbose_name='Cor do subtítulo'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='hero_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Cor do título principal'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='menu_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do menu'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='projects_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Cor da borda'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='projects_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Cor do botão'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='projects_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Projetos – Cor da descrição'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='projects_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Cor do título'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='services_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Cor da borda'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='services_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Cor do botão'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='services_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Serviços – Cor da descrição'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='services_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Cor do título'),
        ),
        migrations.AlterField(
            model_name='sitetheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
