# Generated by Django 5.2.9 on 2026-01-01 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_contactcontent_homecontent_pagecontent_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel'), ('curriculo', 'Currículo'), ('contato', 'Contato')], max_length=30, unique=True, verbose_name='Página')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título principal')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('texto', models.TextField(blank=True, verbose_name='Texto principal')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='pages/banners/', verbose_name='Banner da página')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
        migrations.CreateModel(
            name='PageTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do menu')),
                ('title_color', models.CharField(default='#fde047', max_length=7, verbose_name='Cor do título')),
                ('subtitle_color', models.CharField(default='#38bdf8', max_length=7, verbose_name='Cor do subtítulo')),
                ('text_color', models.CharField(default='#e5e7eb', max_length=7, verbose_name='Cor do texto')),
                ('services_title_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Título')),
                ('services_text_color', models.CharField(default='#334155', max_length=7, verbose_name='Serviços – Texto')),
                ('services_border_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Borda')),
                ('services_button_color', models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Botão')),
                ('projects_title_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Título')),
                ('projects_text_color', models.CharField(default='#334155', max_length=7, verbose_name='Projetos – Texto')),
                ('projects_border_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Borda')),
                ('projects_button_color', models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Botão')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='web.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Tema da Página',
                'verbose_name_plural': 'Temas da Página',
            },
        ),
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do projeto')),
                ('descricao', models.TextField(max_length=600, verbose_name='Descrição do projeto')),
                ('imagem', models.ImageField(upload_to='projects/', verbose_name='Imagem do projeto')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='web.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Projeto – Card',
                'verbose_name_plural': 'Projetos – Cards',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título do serviço')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição do serviço')),
                ('slug', models.SlugField(verbose_name='Slug (link)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='web.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Serviço – Card',
                'verbose_name_plural': 'Serviços – Cards',
                'ordering': ['ordem'],
            },
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
        migrations.DeleteModel(
            name='PageContent',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SiteTheme',
        ),
        migrations.AlterModelOptions(
            name='contactcontent',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contato'},
        ),
        migrations.AlterModelOptions(
            name='curriculo',
            options={'verbose_name': 'Currículo', 'verbose_name_plural': 'Currículo'},
        ),
        migrations.RemoveField(
            model_name='contactcontent',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='subtitulo_banner',
        ),
        migrations.RemoveField(
            model_name='curriculo',
            name='titulo_banner',
        ),
        migrations.AddField(
            model_name='contactcontent',
            name='page',
            field=models.OneToOneField(blank=True, limit_choices_to={'slug': 'contato'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.page', verbose_name='Página'),
        ),
        migrations.AddField(
            model_name='curriculo',
            name='page',
            field=models.OneToOneField(blank=True, limit_choices_to={'slug': 'curriculo'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.page', verbose_name='Página'),
        ),
    ]
