# Generated by Django 5.2.9 on 2026-01-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_page_pagetheme_projectcard_servicecard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomacoesPage',
            fields=[
            ],
            options={
                'verbose_name': 'Automações',
                'verbose_name_plural': 'Automações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='ContatoPage',
            fields=[
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contato',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='CurriculoPage',
            fields=[
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='ExcelPage',
            fields=[
            ],
            options={
                'verbose_name': 'Excel',
                'verbose_name_plural': 'Excel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PowerBIPage',
            fields=[
            ],
            options={
                'verbose_name': 'Power BI',
                'verbose_name_plural': 'Power BI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PythonPage',
            fields=[
            ],
            options={
                'verbose_name': 'Python',
                'verbose_name_plural': 'Python',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
    ]
