# Generated by Django 5.2.9 on 2026-01-01 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_automacoespage_contatopage_curriculopage_excelpage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculo',
            name='page',
        ),
        migrations.DeleteModel(
            name='AutomacoesPage',
        ),
        migrations.DeleteModel(
            name='ContatoPage',
        ),
        migrations.DeleteModel(
            name='CurriculoPage',
        ),
        migrations.DeleteModel(
            name='ExcelPage',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='PowerBIPage',
        ),
        migrations.DeleteModel(
            name='PythonPage',
        ),
        migrations.AddField(
            model_name='page',
            name='curriculo_folha_1',
            field=models.TextField(blank=True, verbose_name='Currículo – Texto da Folha 1'),
        ),
        migrations.AddField(
            model_name='page',
            name='curriculo_folha_2',
            field=models.TextField(blank=True, verbose_name='Currículo – Texto da Folha 2'),
        ),
        migrations.AddField(
            model_name='page',
            name='curriculo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='curriculo/pdf/', verbose_name='Currículo – PDF'),
        ),
        migrations.AddField(
            model_name='servicecard',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Imagem do serviço'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='page',
            field=models.OneToOneField(default=1, limit_choices_to={'slug': 'contato'}, on_delete=django.db.models.deletion.CASCADE, to='web.page', verbose_name='Página'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='menu_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='projects_border_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='projects_button_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='projects_text_color',
            field=models.CharField(default='#334155', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='projects_title_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='services_border_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='services_button_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='services_text_color',
            field=models.CharField(default='#334155', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='services_title_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='subtitle_color',
            field=models.CharField(default='#38bdf8', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='text_color',
            field=models.CharField(default='#e5e7eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='pagetheme',
            name='title_color',
            field=models.CharField(default='#fde047', max_length=7),
        ),
        migrations.DeleteModel(
            name='Curriculo',
        ),
    ]
