# Generated by Django 5.2.9 on 2026-01-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_remove_curriculo_page_delete_automacoespage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['ordem'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem no menu'),
        ),
    ]
