# Generated by Django 5.2.9 on 2026-01-02 14:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_page_options_page_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomacoesPage',
            fields=[
            ],
            options={
                'verbose_name': 'Automações',
                'verbose_name_plural': 'Automações',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='CurriculoPage',
            fields=[
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='ExcelPage',
            fields=[
            ],
            options={
                'verbose_name': 'Excel',
                'verbose_name_plural': 'Excel',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PowerBIPage',
            fields=[
            ],
            options={
                'verbose_name': 'Power BI',
                'verbose_name_plural': 'Power BI',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.CreateModel(
            name='PythonPage',
            fields=[
            ],
            options={
                'verbose_name': 'Python',
                'verbose_name_plural': 'Python',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('web.page',),
        ),
        migrations.AlterModelOptions(
            name='contactcontent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='projectcard',
            options={'ordering': ['ordem']},
        ),
        migrations.AlterModelOptions(
            name='servicecard',
            options={'ordering': ['ordem']},
        ),
        
        migrations.AddField(
            model_name='page',
            name='projects_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Borda'),
        ),
        migrations.AddField(
            model_name='page',
            name='projects_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Botão'),
        ),
        migrations.AddField(
            model_name='page',
            name='projects_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Projetos – Texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='projects_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Projetos – Título'),
        ),
        migrations.AddField(
            model_name='page',
            name='services_border_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Borda'),
        ),
        migrations.AddField(
            model_name='page',
            name='services_button_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Botão'),
        ),
        migrations.AddField(
            model_name='page',
            name='services_text_color',
            field=models.CharField(default='#334155', max_length=7, verbose_name='Serviços – Texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='services_title_color',
            field=models.CharField(default='#fde047', max_length=7, verbose_name='Serviços – Título'),
        ),
        migrations.AddField(
            model_name='page',
            name='subtitulo_color',
            field=models.CharField(default='#cbd5e1', max_length=7, verbose_name='Cor do subtítulo'),
        ),
        migrations.AddField(
            model_name='page',
            name='texto_color',
            field=models.CharField(default='#e5e7eb', max_length=7, verbose_name='Cor do texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='titulo_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do título'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='page',
            field=models.OneToOneField(limit_choices_to={'slug': 'contato'}, on_delete=django.db.models.deletion.CASCADE, to='web.page'),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='telefone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contactcontent',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='page',
            name='curriculo_folha_1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Currículo – Folha 1'),
        ),
        migrations.AlterField(
            model_name='page',
            name='curriculo_folha_2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Currículo – Folha 2'),
        ),
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Hero – Subtítulo'),
        ),
        migrations.AlterField(
            model_name='page',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Texto principal'),
        ),
        migrations.AlterField(
            model_name='page',
            name='titulo',
            field=ckeditor.fields.RichTextField(verbose_name='Hero – Título'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='imagem',
            field=models.ImageField(upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='web.page'),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='projectcard',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='descricao',
            field=ckeditor.fields.RichTextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='web.page'),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='servicecard',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PageTheme',
        ),
    ]
