# Generated by Django 5.2.9 on 2026-01-02 15:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_automacoespage_curriculopage_excelpage_homepage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='ordem',
        ),
        migrations.AddField(
            model_name='page',
            name='footer_bg_color',
            field=models.CharField(default='#020617', max_length=7, verbose_name='Footer – Cor de fundo'),
        ),
        migrations.AddField(
            model_name='page',
            name='footer_conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Footer – Conteúdo'),
        ),
        migrations.AddField(
            model_name='page',
            name='footer_text_color',
            field=models.CharField(default='#cbd5e1', max_length=7, verbose_name='Footer – Cor do texto'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_bg_color',
            field=models.CharField(default='#0f172a', max_length=7, verbose_name='Menu – Cor de fundo'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_conteudo',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Menu – Conteúdo'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu_text_color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Menu – Cor do texto'),
        ),
    ]
