# Generated by Django 5.2.9 on 2026-01-06 17:28

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('home', 'Home'), ('python', 'Python'), ('powerbi', 'Power BI'), ('automacoes', 'Automações'), ('excel', 'Excel'), ('curriculo', 'Currículo'), ('contato', 'Contato')], max_length=50, unique=True)),
                ('banner_title', models.CharField(max_length=255, verbose_name='Título do Banner')),
                ('banner_subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo do Banner')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folha_1', ckeditor.fields.RichTextField(verbose_name='Folha 1')),
                ('folha_2', ckeditor.fields.RichTextField(verbose_name='Folha 2')),
                ('page', models.OneToOneField(limit_choices_to={'slug': 'curriculo'}, on_delete=django.db.models.deletion.CASCADE, to='servicesbi.page')),
            ],
        ),
        migrations.CreateModel(
            name='ContatoText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', ckeditor.fields.RichTextField(verbose_name='Texto introdutório')),
                ('form_title', models.CharField(max_length=150, verbose_name='Título do Formulário')),
                ('page', models.OneToOneField(limit_choices_to={'slug': 'contato'}, on_delete=django.db.models.deletion.CASCADE, to='servicesbi.page')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Projeto')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição do Projeto')),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='servicesbi.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título do Serviço')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Descrição do Serviço')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='services/icons/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='servicesbi.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
