# Generated by Django 5.2.9 on 2026-01-06 18:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesbi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='banner_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Descrição do Banner'),
        ),
        migrations.AddField(
            model_name='page',
            name='banner_eyebrow',
            field=models.CharField(blank=True, max_length=100, verbose_name='Texto superior do Banner'),
        ),
    ]
